accounts/urls.py
from .views import *
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('', signin, name='signin'),
    path('logout', logout, name='logout'),
]

main/urls.py
from .views import *
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('search/', include('search.urls', namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from .views import *
from django.urls import path

app_name = 'search'

urlpatterns = [
    path('', search, name='search'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    department = models.CharField(max_length=100)

search/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import User
from django.views.decorators.csrf import csrf_exempt
from django.contrib import auth, messages

# Create your views here.
# 로그인 부분
@csrf_exempt
def signin(request):
    if request.method == 'POST':
        user_email = request.POST['email'] # 이메일을 입력받는다.
        print(request.POST['email'])
        password = request.POST['password'] # 비번을 입력받는다.
        print(request.POST['password'])
        user = auth.authenticate(request, username=user_email, password=password) # 아이디와 비번을 가져와서 확인한다.
        if user is not None: # 로그인 부분
            print('맞음')
            auth.login(request, user)
            return redirect('main:home') # 아이디 비번 맞으면 다른곳으로 들어감
        else:
            # 딕셔너리에 에러메세지를 전달하고 다시 login.html 화면으로 돌아간다.
            messages.warning(request, '아이디 또는 비밀번호를 확인하세요.')
            return redirect('accounts:signin')
    return render(request, 'accounts/signin.html')

# 로그아웃 부분
def logout(request):
    auth.logout(request)
    return redirect('accounts:signin')


# 회원가입
def signup(request):
    if request.method == 'POST':
        if User.objects.filter(username=request.POST['email']).exists():  # 이메일 중복 체크
            messages.warning(request, '중복된 이메일 입니다.')
        elif User.objects.filter(first_name=request.POST['nickname']).exists():  # 닉네임 중복 체크
            messages.warning(request, '중복된 닉네임 입니다.')
        if request.POST['password'] == request.POST['password_check']: # 비번 같은지 체크
            user = User.objects.create_user( # 새로운 학습자를 만들어서 DB에 저장되는것이다.
                                            last_name=request.POST['last_name'],
                                            username=request.POST['email'],
                                            password=request.POST['password'],
                                            email=request.POST['email'],
                                            department=request.POST['department'],
                                            first_name=request.POST['nickname'])
            user.save()
            return redirect('accounts:signin')
        else:
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 다릅니다.'})
        return render(request, 'accounts/signup.html')
    return render(request, 'accounts/signup.html')

main/views.py
from django.shortcuts import render

# Create your views here.

# 메인화면
def home(request):
    return render(request, 'main/main.html')

search/views.py
from django.shortcuts import render

# Create your views here.

# 검색창 메인.
def search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        return render(request, 'search/search.html', {})
    return render(request, 'search/search.html')

templates/accounts/signin.html
{% extends "base.html" %}
{% load static %}

{% block title %}
로그인
{% endblock title %}

{% block content %}


    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
    <script>
        window.setTimeout(function() {
        $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove(); }); }, 4000);
    </script>
    {% endif %}


    <!-- ====== Banner Start ====== -->
    <section class="ud-page-banner">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="ud-banner-content">
              <h1>로그인</h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Banner End ====== -->

    <!-- ====== Login Start ====== -->
    <section class="ud-login">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="ud-login-wrapper">
              <div class="ud-login-logo">
                <img src="{% static 'assets/images/logo/logo-2.svg' %}" alt="logo" />
              </div>
              <form class="ud-login-form" action="{% url 'accounts:signin' %}" method="post">
                {% csrf_token %}
                <div class="ud-form-group">
                  <input
                    type="text"
                    name="email"
                    placeholder="Email"
                  />
                </div>
                <div class="ud-form-group">
                  <input
                    type="password"
                    name="password"
                    placeholder="Password"
                  />
                </div>
                <div class="ud-form-group">
                  <button type="submit" class="ud-main-btn w-100">Login</button>
                </div>
              </form>

              <div class="ud-socials-connect">
                <p>Connect With</p>

                <ul>
                  <li>
                    <a href="javascript:void(0)" class="facebook">
                      <i class="lni lni-facebook-filled"></i>
                    </a>
                  </li>
                  <li>
                    <a href="javascript:void(0)" class="twitter">
                      <i class="lni lni-twitter-filled"></i>
                    </a>
                  </li>
                  <li>
                    <a href="javascript:void(0)" class="google">
                      <i class="lni lni-google"></i>
                    </a>
                  </li>
                </ul>
              </div>

              <a class="forget-pass" href="javascript:void(0)">
                Forget Password?
              </a>
              <p class="signup-option">
                Not a member yet? <a href="javascript:void(0)"> Sign Up </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Login End ====== -->
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}
회원가입
{% endblock title %}

{% block content %}


    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
    <script>
        window.setTimeout(function() {
        $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove(); }); }, 4000);
    </script>
    {% endif %}


    <!-- ====== Banner Start ====== -->
    <section class="ud-page-banner">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="ud-banner-content">
              <h1>회원가입</h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Banner End ====== -->


    <!-- ====== Login Start ====== -->
    <section class="ud-login">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="ud-login-wrapper">
              <div class="ud-login-logo">
                <img src="{% static 'assets/images/logo/logo-2.svg' %}" alt="logo" />
              </div>
              <form class="ud-login-form" action="{% url 'accounts:signup' %}" method="post">
                {% csrf_token %}
                <div class="ud-form-group">
                  <input
                    type="text"
                    placeholder="이름"
                    name="last_name"
                    maxlength="7"
                  />
                </div>
                <div class="ud-form-group">
                  <input
                    type="email"
                    name="email"
                    placeholder="Email"
                  />
                </div>
                <div class="ud-form-group">
                  <input
                    type="password"
                    name="password"
                    placeholder="비밀번호"
                  />
                </div>
                <div class="ud-form-group">
                  <input
                    type="password"
                    name="password_check"
                    placeholder="비밀번호 확인"
                  />
                </div>
                <div class="ud-form-group">
                  <input
                    type="text"
                    placeholder="닉네임"
                    name="nickname"
                    maxlength="8"
                  />
                </div>
                <div class="ud-form-group">
                  <input
                    type="text"
                    placeholder="소속"
                    name="department"
                    maxlength="20"
                  />
                </div>
                <div class="ud-form-group">
                  <button type="submit" class="ud-main-btn w-100">회원가입</button>
                </div>
              </form>

              <div class="ud-socials-connect">
                <p>Connect With</p>

                <ul>
                  <li>
                    <a href="javascript:void(0)" class="facebook">
                      <i class="lni lni-facebook-filled"></i>
                    </a>
                  </li>
                  <li>
                    <a href="javascript:void(0)" class="twitter">
                      <i class="lni lni-twitter-filled"></i>
                    </a>
                  </li>
                  <li>
                    <a href="javascript:void(0)" class="google">
                      <i class="lni lni-google"></i>
                    </a>
                  </li>
                </ul>
              </div>

              <a class="forget-pass" href="javascript:void(0)">
                Forget Password?
              </a>
              <p class="signup-option">
                Not a member yet? <a href="javascript:void(0)"> Sign Up </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Login End ====== -->
{% endblock %}

templates/base.html
{% load static %}

<html lang="en">
{% include 'head.html' %}
<title>
{% block title %}
메인
{% endblock title %}
</title>
  <body>
    <!-- ====== Header Start ====== -->
    <header class="ud-header">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <nav class="navbar navbar-expand-lg">
              <a class="navbar-brand" href="{% url 'main:home' %}">
                <img src="{% static 'assets/images/logo/logo.svg' %}" alt="Logo" />
              </a>
              <button class="navbar-toggler">
                <span class="toggler-icon"> </span>
                <span class="toggler-icon"> </span>
                <span class="toggler-icon"> </span>
              </button>

              <div class="navbar-collapse">
                <ul id="nav" class="navbar-nav mx-auto">
                  <li class="nav-item">
                    <a class="ud-submenu-link" href="{% url 'main:home' %}">Home</a>
                  </li>
                  <li class="nav-item nav-item-has-children">
                    <a href="javascript:void(0)"> 커리어 탐색 </a>
                    <ul class="ud-submenu">
                      <li class="ud-submenu-item">
                        <a href="https://www.work.go.kr/consltJobCarpa/jobPsyExamNew/jobPsyExamYouthList.do" class="ud-submenu-link">
                          워크넷 간단 검사(청소년)
                        </a>
                      </li>
                      <li class="ud-submenu-item">
                        <a href="https://www.work.go.kr/consltJobCarpa/jobPsyExamNew/jobPsyExamAdultList.do" class="ud-submenu-link">
                          워크넷 간단 검사(성인)
                        </a>
                      </li>
                      <li class="ud-submenu-item">
                        <a href="https://www.work.go.kr/consltJobCarpa/srch/jobRecommend/jobRecommend.do" class="ud-submenu-link">
                          워크넷 간단 검사(직무기반 직업추천)
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="ud-submenu-link" href="{% url 'search:search' %}">직업 및 마이크로디그리 탐색</a>
                  </li>
                  <li class="nav-item">
                    <a class="ud-submenu-link" href="{% url 'search:search' %}">강좌 검색</a>
                  </li>
                </ul>
              </div>

              <div class="navbar-btn d-none d-sm-inline-block">
                <a href="{% url 'accounts:signin' %}" class="ud-main-btn ud-login-btn">
                  Sign In
                </a>
                <a class="ud-main-btn ud-white-btn" href="{% url 'accounts:signup' %}">
                  Sign Up
                </a>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <!-- ====== Header End ====== -->

    <!-- ====== 시작 -->
    {% block content %}

    {% endblock %}
    <!-- ====== 끝 -->

    {% include 'footer.html' %}

    <!-- ====== Back To Top Start ====== -->
    <a href="javascript:void(0)" class="back-to-top">
      <i class="lni lni-chevron-up"> </i>
    </a>
    <!-- ====== Back To Top End ====== -->

    <!-- ====== All Javascript Files ====== -->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script>
      // ==== for menu scroll
      const pageLink = document.querySelectorAll(".ud-menu-scroll");

      pageLink.forEach((elem) => {
        elem.addEventListener("click", (e) => {
          e.preventDefault();
          document.querySelector(elem.getAttribute("href")).scrollIntoView({
            behavior: "smooth",
            offsetTop: 1 - 60,
          });
        });
      });

      // section menu active
      function onScroll(event) {
        const sections = document.querySelectorAll(".ud-menu-scroll");
        const scrollPos =
          window.pageYOffset ||
          document.documentElement.scrollTop ||
          document.body.scrollTop;

        for (let i = 0; i < sections.length; i++) {
          const currLink = sections[i];
          const val = currLink.getAttribute("href");
          const refElement = document.querySelector(val);
          const scrollTopMinus = scrollPos + 73;
          if (
            refElement.offsetTop <= scrollTopMinus &&
            refElement.offsetTop + refElement.offsetHeight > scrollTopMinus
          ) {
            document
              .querySelector(".ud-menu-scroll")
              .classList.remove("active");
            currLink.classList.add("active");
          } else {
            currLink.classList.remove("active");
          }
        }
      }

      window.document.addEventListener("scroll", onScroll);
    </script>
  </body>
</html>

templates/footer.html
{% load static %}

<!-- ====== Footer Start ====== -->
    <footer class="ud-footer wow fadeInUp" data-wow-delay=".15s">
      <div class="shape shape-1">
        <img src="{% static 'assets/images/footer/shape-1.svg' %}" alt="shape" />
      </div>
      <div class="shape shape-2">
        <img src="{% static 'assets/images/footer/shape-2.svg' %}" alt="shape" />
      </div>
      <div class="shape shape-3">
        <img src="{% static 'assets/images/footer/shape-3.svg' %}" alt="shape" />
      </div>
      <div class="ud-footer-widgets">
        <div class="container">
          <div class="row">
            <div class="col-xl-3 col-lg-4 col-md-6">
              <div class="ud-widget">
                <a href="{% url 'main:home' %}" class="ud-footer-logo">
                  <img src="{% static 'assets/images/logo/logo.svg' %}" alt="logo" />
                </a>
                <p class="ud-widget-desc">
                  We create digital experiences for brands and companies by
                  using technology.
                </p>
                <ul class="ud-widget-socials">
                  <li>
                    <a href="https://twitter.com/MusharofChy">
                      <i class="lni lni-facebook-filled"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://twitter.com/MusharofChy">
                      <i class="lni lni-twitter-filled"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://twitter.com/MusharofChy">
                      <i class="lni lni-instagram-filled"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://twitter.com/MusharofChy">
                      <i class="lni lni-linkedin-original"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            <div class="col-xl-2 col-lg-2 col-md-6 col-sm-6">
              <div class="ud-widget">
                <h5 class="ud-widget-title">About Us</h5>
                <ul class="ud-widget-links">
                  <li>
                    <a href="{% url 'main:home' %}">Home</a>
                  </li>
                  <li>
                    <a href="javascript:void(0)">Features</a>
                  </li>
                  <li>
                    <a href="javascript:void(0)">About</a>
                  </li>
                  <li>
                    <a href="javascript:void(0)">Testimonial</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-xl-2 col-lg-3 col-md-6 col-sm-6">
              <div class="ud-widget">
                <h5 class="ud-widget-title">Features</h5>
                <ul class="ud-widget-links">
                  <li>
                    <a href="javascript:void(0)">How it works</a>
                  </li>
                  <li>
                    <a href="javascript:void(0)">Privacy policy</a>
                  </li>
                  <li>
                    <a href="javascript:void(0)">Terms of service</a>
                  </li>
                  <li>
                    <a href="javascript:void(0)">Refund policy</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-xl-2 col-lg-3 col-md-6 col-sm-6">
              <div class="ud-widget">
                <h5 class="ud-widget-title">Our Products</h5>
                <ul class="ud-widget-links">
                  <li>
                    <a
                      href="https://lineicons.com/"
                      rel="nofollow noopner"
                      target="_blank"
                      >Lineicons
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://ecommercehtml.com/"
                      rel="nofollow noopner"
                      target="_blank"
                      >Ecommerce HTML</a
                    >
                  </li>
                  <li>
                    <a
                      href="https://ayroui.com/"
                      rel="nofollow noopner"
                      target="_blank"
                      >Ayro UI</a
                    >
                  </li>
                  <li>
                    <a
                      href="https://graygrids.com/"
                      rel="nofollow noopner"
                      target="_blank"
                      >Plain Admin</a
                    >
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-8 col-sm-10">
              <div class="ud-widget">
                <h5 class="ud-widget-title">Partners</h5>
                <ul class="ud-widget-brands">
                  <li>
                    <a
                      href="https://ayroui.com/"
                      rel="nofollow noopner"
                      target="_blank"
                    >
                      <img
                        src="{% static 'assets/images/footer/brands/ayroui.svg' %}"
                        alt="ayroui"
                      />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://ecommercehtml.com/"
                      rel="nofollow noopner"
                      target="_blank"
                    >
                      <img
                        src="{% static 'assets/images/footer/brands/ecommerce-html.svg' %}"
                        alt="ecommerce-html"
                      />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://graygrids.com/"
                      rel="nofollow noopner"
                      target="_blank"
                    >
                      <img
                        src="{% static 'assets/images/footer/brands/graygrids.svg' %}"
                        alt="graygrids"
                      />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://lineicons.com/"
                      rel="nofollow noopner"
                      target="_blank"
                    >
                      <img
                        src="{% static 'assets/images/footer/brands/lineicons.svg' %}"
                        alt="lineicons"
                      />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://uideck.com/"
                      rel="nofollow noopner"
                      target="_blank"
                    >
                      <img
                        src="{% static 'assets/images/footer/brands/uideck.svg' %}"
                        alt="uideck"
                      />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://tailwindtemplates.co/"
                      rel="nofollow noopner"
                      target="_blank"
                    >
                      <img
                        src="{% static 'assets/images/footer/brands/tailwindtemplates.svg' %}"
                        alt="tailwindtemplates"
                      />
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="ud-footer-bottom">
        <div class="container">
          <div class="row">
            <div class="col-md-8">
              <ul class="ud-footer-bottom-left">
                <li>
                  <a href="javascript:void(0)">Privacy policy</a>
                </li>
                <li>
                  <a href="javascript:void(0)">Support policy</a>
                </li>
                <li>
                  <a href="javascript:void(0)">Terms of service</a>
                </li>
              </ul>
            </div>
            <div class="col-md-4">
              <p class="ud-footer-bottom-right">
                Designed and Developed by
                <a href="https://uideck.com" rel="nofollow">UIdeck</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- ====== Footer End ====== -->

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Primary Meta Tags -->
<meta name="title" content="Play - Free Open Source HTML Bootstrap Template by UIdeck">
<meta name="description" content="Play - Free Open Source HTML Bootstrap Template by UIdeck Team">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://uideck.com/play/">
<meta property="og:title" content="Play - Free Open Source HTML Bootstrap Template by UIdeck">
<meta property="og:description" content="Play - Free Open Source HTML Bootstrap Template by UIdeck Team">
<meta property="og:image" content="https://uideck.com/wp-content/uploads/2021/09/play-meta-bs.jpg">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://uideck.com/play/">
<meta property="twitter:title" content="Play - Free Open Source HTML Bootstrap Template by UIdeck">
<meta property="twitter:description" content="Play - Free Open Source HTML Bootstrap Template by UIdeck Team">
<meta property="twitter:image" content="https://uideck.com/wp-content/uploads/2021/09/play-meta-bs.jpg">

    <!--====== Favicon Icon ======-->
    <link
      rel="shortcut icon"
      href="{% static 'assets/images/favicon.svg' %}"
      type="image/svg"
    />

    <!-- ===== All CSS files ===== -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/lineicons.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/ud-styles.css' %}" />

    {#    아이콘 사용하기 위한 것임.#}
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">

  </head>

templates/main/main.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- ====== 시작 ====== -->
    <section class="ud-hero" id="home">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="ud-hero-content wow fadeInUp" data-wow-delay=".2s">
              <h1 class="ud-hero-title">
                직업 설계를 위한 전략적 학습<br>(Study for Strategic Job Planning)
              </h1>
              <p class="ud-hero-desc">
                "성공적 커리어 설계 지원 <b>학습관리</b>"
              </p>
              <ul class="ud-hero-buttons">
                <li>
                  <a href="https://links.uideck.com/play-bootstrap-download" rel="nofollow noopener" target="_blank" class="ud-main-btn ud-white-btn">
                    Download Now
                  </a>
                </li>
                <li>
                  <a href="https://github.com/uideck/play-bootstrap" rel="nofollow noopener" target="_blank" class="ud-main-btn ud-link-btn">
                    Learn More <i class="lni lni-arrow-right"></i>
                  </a>
                </li>
              </ul>
            </div>
            <div
              class="ud-hero-brands-wrapper wow fadeInUp"
              data-wow-delay=".3s"
            >
              <img src="{% static 'assets/images/hero/brand.svg' %}" alt="brand" />
            </div>
            <div class="ud-hero-image wow fadeInUp" data-wow-delay=".25s">
              <img src="{% static 'assets/images/hero/system_goal.png' %}" alt="hero-image" />
              <img
                src="{% static 'assets/images/hero/dotted-shape.svg' %}"
                alt="shape"
                class="shape shape-1"
              />
              <img
                src="{% static 'assets/images/hero/dotted-shape.svg' %}"
                alt="shape"
                class="shape shape-2"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== 끝 ====== -->
{% endblock %}